[package]
name = "taskmaster"
version = "0.1.0"
edition = "2021"

[dependencies]
simplelog = "0.12.1"
libc = "0.2.153"
log = { version = "0.4.20", features = ["serde"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_with = "3.6.1"
toml = "0.8.10"
users = "0.11.0"
