[package]
name = "taskmaster"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
serde = { version = "1.0.197", features = ["derive"] }
simple_logger = "4.3.3"
toml = "0.8.10"
users = "0.11.0"
