use serde::Deserialize;

#[allow(clippy::upper_case_acronyms)]
#[derive(Deserialize, Debug)]
pub enum Signal {
	SIGHUP,
	SIGINT,
	SIGQUIT,
	SIGILL,
	SIGTRAP,
	SIGABRT,
	SIGBUS,
	SIGFPE,
	SIGKILL,
	SIGUSR1,
	SIGSEGV,
	SIGUSR2,
	SIGPIPE,
	SIGALRM,
	SIGTERM,
	SIGSTKFLT,
	SIGCHLD,
	SIGCONT,
	SIGSTOP,
	SIGTSTP,
	SIGTTIN,
	SIGTTOU,
	SIGURG,
	SIGXCPU,
	SIGXFSZ,
	SIGVTALRM,
	SIGPROF,
	SIGWINCH,
	SIGIO,
	SIGPOLL,
	SIGPWR,
	SIGSYS,
	SIGUNUSED,
}

impl Signal {
	pub fn to_u8(&self) -> u8 {
		match self {
			Signal::SIGHUP => 1,
			Signal::SIGINT => 2,
			Signal::SIGQUIT => 3,
			Signal::SIGILL => 4,
			Signal::SIGTRAP => 5,
			Signal::SIGABRT => 6,
			Signal::SIGBUS => 7,
			Signal::SIGFPE => 8,
			Signal::SIGKILL => 9,
			Signal::SIGUSR1 => 10,
			Signal::SIGSEGV => 11,
			Signal::SIGUSR2 => 12,
			Signal::SIGPIPE => 13,
			Signal::SIGALRM => 14,
			Signal::SIGTERM => 15,
			Signal::SIGSTKFLT => 16,
			Signal::SIGCHLD => 17,
			Signal::SIGCONT => 18,
			Signal::SIGSTOP => 19,
			Signal::SIGTSTP => 20,
			Signal::SIGTTIN => 21,
			Signal::SIGTTOU => 22,
			Signal::SIGURG => 23,
			Signal::SIGXCPU => 24,
			Signal::SIGXFSZ => 25,
			Signal::SIGVTALRM => 26,
			Signal::SIGPROF => 27,
			Signal::SIGWINCH => 28,
			Signal::SIGIO => 29,
			Signal::SIGPOLL => 29,
			Signal::SIGPWR => 30,
			Signal::SIGSYS => 31,
			Signal::SIGUNUSED => 31,
		}
	}
}