user = "mirsella"
logfile = "taskmaster.log"
loglevel = "debug"

[[program]]
name = "ls"
command = "yes"
processes = 1
start_policy = "auto"
valid_exit_codes = [0]
min_runtime = 1
restart_policy = "never"
max_restarts = 3
valid_signal = "SIGSTOP"
stdin = "/dev/stdin"
stdout = "test.log"
args = []
env = []
cwd = "/tmp"
umask = "0002"
user = "root"

[[program]]
name = "yes2"
command = "yes"
processes = 1
args = ["Hello les amis"]
