user = "nonrootuser"

[[program]]
command = "ls"
processes = 1
start = "manual"
exit_codes = [0]
min_runtime = 1
restart_policy = "never"
max_restarts = 3
exit_signal = "SIGKILL"
stdin = "/dev/null"
stdout = "/dev/null"
env = ['LS_COLORS=rs=01;31:*', 'LS_OPTIONS=-lt']
cwd = "/tmp"
umask = "0002"
