loglevel = "trace"

[[program]]
name = "exit"
command = "python3"
processes = 30
args = ["tests/exit.py"]

[[program]]
name = "exit and signals"
command = "python3"
processes = 30
restart_policy = "unexpectedexit"
max_restarts = 2
min_runtime = 5
args = ["tests/exit_signal.py"]